# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Set plugins
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
  - jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Fred Dickinson'
description: ''
permalink: pretty
encoding: utf-8
lang: en-GB
title: "Fred Dickinson"
# logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Empty description."
repo: "https://github.com/fredwdickinson/fredwdickinson.github.io"
email: "fredsterdickinson@gmail.com"

# Pagination
# paginate: 5
# paginate_path: blog/page:num

# Header nav
navigation_header:
  - title: Home
    url: /
  - title: Tutoring
    url: /pages/tutoring/
  - title: Maths
    url: /pages/maths/
  - title: Sport
    url: /pages/sport/
  - title: Contact
    url: /pages/contact/

# Footer nav
navigation_footer:
  - title: Top
    url: "#top"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
